In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
tree_4_6 = DecisionTreeClassifier(criterion='entropy', random_state=42)
tree_5 = DecisionTreeClassifier(criterion='entropy', random_state=42)
tree_3 = DecisionTreeClassifier(criterion='entropy', random_state=42)
tree_7_8 = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [3]:
train_4_6 = pd.read_csv('train_data_4_6.csv')

In [4]:
train_5 = pd.read_csv('train_data_5.csv')

In [5]:
train_3 = pd.read_csv('train_data_3.csv')

In [6]:
train_7_8 = pd.read_csv('train_data_7_8.csv')

In [7]:
pred_4_6 = pd.read_csv('pred_4_6.csv')

In [8]:
pred_5 = pd.read_csv('pred_5.csv')

In [9]:
pred_3 = pd.read_csv('pred_3.csv')

In [10]:
pred_7_8 = pd.read_csv('pred_7_8.csv')

In [11]:
train_4_6

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    2          0       4           3                 2          2   
1       1    1          3       3           1                 3          1   
2       1    3          1       0           3                 3          1   
3       1    3          1       2           0                 2          2   
4       0    3          1       1           3                 3          3   

   Motivation  Attitude  Intention  Ownership  1  ER  2  ER.1  3  ER.2  
0           1         0          0          0  0   2  1     8  1     4  
1           2         6          3          4  1   0  1     4  1    12  
2           0         1          1          4  1   0  0     2  0     0  
3           3         1          2          3  1   3  1    12  0     5  
4           3         5          5          2  1  10  0    10  0    10

In [12]:
train_5

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    2          0       4           3                 2          2   
1       1    1          3       3           1                 3          1   
2       1    3          1       0           3                 3          1   
3       0    3          1       1           3                 3          3   

   Motivation  Attitude  Intention  ...  1  ER  2  ER.1  3  ER.2  4  ER.3  5  \
0           1         0          0  ...  0   2  1     8  1     4  1     7  1   
1           2         6          3  ...  1   0  1     4  1    12  1    10  1   
2           0         1          1  ...  1   0  0     2  0     0  0     7  0   
3           3         5          5  ...  1  10  0    10  0    10  0    12  0   

   ER.4  
0     9  
1    10  
2     0  
3    12  

[4 rows x 21 columns]

In [13]:
train_3

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    2          0       4           3                 2          2   
1       1    1          3       3           1                 3          1   
2       0    3          1       1           3                 3          3   

   Motivation  Attitude  Intention  ...  10  ER.9  11  ER.10  12  ER.11  13  \
0           1         0          0  ...   1     3   1      7   1      6   0   
1           2         6          3  ...   1    10   1     10   1     12   1   
2           3         5          5  ...   0    12   0     12   0     10   0   

   ER.12  14  ER.13  
0      0   0      0  
1     12   1     10  
2     12   0     12  

[3 rows x 39 columns]

In [14]:
train_7_8

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    2          0       4           3                 2          2   
1       1    1          3       3           1                 3          1   
2       1    3          1       0           3                 3          1   
3       1    3          1       0           0                 1          0   
4       1    3          1       2           0                 2          2   
5       0    3          0       2           2                 1          2   
6       0    3          1       1           3                 3          3   

   Motivation  Attitude  Intention  Ownership  1  ER  
0           1         0          0          0  0   2  
1           2         6          3          4  1   0  
2           0         1          1          4  1   0  
3           3         1          2          2  0   0  
4           3         1          2          3  1   3  
5           5         0          4          1  0   1  
6           3         5          5          2  1  10

In [15]:
pred_4_6

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    3          1       0           0                 1          0   
1       0    3          0       2           2                 1          2   

   Motivation  Attitude  Intention  Ownership  1  ER  2  ER.1  
0           3         1          2          2  0   0  1     0  
1           5         0          4          1  0   1  1     6

In [16]:
pred_5

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    3          1       2           0                 2          2   

   Motivation  Attitude  Intention  Ownership  1  ER  2  ER.1  3  ER.2  4  \
0           3         1          2          3  1   3  1    12  0     5  1   

   ER.3  
0    11

In [17]:
pred_3

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    3          1       0           3                 3          1   

   Motivation  Attitude  Intention  ...  9  ER.8  10  ER.9  11  ER.10  12  \
0           0         1          1  ...  0     0   0     0   0      0   0   

   ER.11  13  ER.12  
0      0   1     12  

[1 rows x 37 columns]

In [18]:
pred_7_8

Gender  Age  Ethnicity  Income  Work hours  Health condition  Education  \
0       1    0          3       2           3                 2          2   
1       0    3          3       4           3                 2          3   

   Motivation  Attitude  Intention  Ownership  
0           4         4          4          5  
1           5         3          4          5

In [19]:
y_4_6 = train_4_6.iloc[:,-1]

In [20]:
y_5 = train_5.iloc[:,-1]

In [21]:
y_3 = train_3.iloc[:,-1]

In [22]:
y_7_8 = train_7_8.iloc[:,-1]

In [23]:
X_4_6 = train_4_6.iloc[:,0:-1]

In [24]:
X_5 = train_5.iloc[:,0:-1]

In [25]:
X_3 = train_3.iloc[:,0:-1]

In [26]:
X_7_8 = train_7_8.iloc[:,0:-1]

In [27]:
tree_4_6.fit(X_4_6, y_4_6)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [28]:
tree_5.fit(X_5, y_5)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [29]:
tree_3.fit(X_3, y_3)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [30]:
tree_7_8.fit(X_7_8, y_7_8)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [31]:
diet_4_6 = pd.DataFrame({'2':[1,1]})
phys_4_6 = pd.DataFrame({'2':[0,0]})
diet_ = pd.DataFrame({'2': [1]})
phys_ = pd.DataFrame({'2': [0]})

In [32]:
tree_4_6.predict(pd.concat([pred_4_6, phys_4_6], axis=1))

array([0, 4], dtype=int64)

In [33]:
tree_4_6.predict(pd.concat([pred_4_6, diet_4_6], axis=1))

array([0, 4], dtype=int64)

In [34]:
tree_5.predict(pd.concat([pred_5, phys_], axis=1))

array([0], dtype=int64)

In [35]:
tree_5.predict(pd.concat([pred_5, diet_], axis=1))

array([0], dtype=int64)

In [36]:
tree_3.predict(pd.concat([pred_3, phys_], axis=1))

array([10], dtype=int64)

In [37]:
tree_3.predict(pd.concat([pred_3, diet_], axis=1))

array([10], dtype=int64)

In [38]:
tree_7_8.predict(pd.concat([pred_7_8, phys_4_6], axis=1))

array([3, 3], dtype=int64)

In [39]:
tree_7_8.predict(pd.concat([pred_7_8, diet_4_6], axis=1))

array([3, 3], dtype=int64)